[[redirects]]
  from = "/welding-consumables-uae"
  to = "/articles/welding-consumables-uae.html"
  status = 200

[[redirects]]
  from = "/fm-second-vendor-uae"
  to = "/articles/fm-second-vendor-uae.html"
  status = 200

[[redirects]]
  from = "/vendor-list-uae"
  to = "/articles/vendor-list-uae.html"
  status = 200

[[redirects]]
  from = "/mro-procurement-2026"
  to = "/articles/mro-procurement-2026.html"
  status = 200
